services:
    mysql:
        image: mysql:latest
        container_name: mysql_container
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: 'db_hgstore'
        restart: always
        networks:
            - appSdrinks-online

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-container
        restart: always
        depends_on:
            - mysql
        ports:
            - '90:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            UPLOAD_LIMIT: 500M
        networks:
            - appSdrinks-online
networks:
    appSdrinks-online:
        name: appSdrinks-online
        driver: bridge
# docker-compose -f ./deployments.yml up -d
